#:schema https://raw.githubusercontent.com/yunanwg/brilliant-CV/main/metadata.toml.schema.json

# Set the output language
# INFO: value must matches folder suffix; i.e "zh" -> "./modules_zh"
language = "fr"

[layout]
    # Optional values: skyblue, red, nephritis, concrete, darknight
    # You can also use a custom color by hex code i.e. "#1E90FF"
    awesome_color = "darknight"

    # Skips are for controlling the spacing between sections and entries
    before_section_skip = "1pt"
    before_entry_skip = "1pt"
    before_entry_description_skip = "1pt"

    # Optional: sets paper size and margins. Possible values: a4 (default), us-letter
    paper_size = "a4"

    # Optional: sets the width of the right column of a cvEntry. If not set, values known to work well are used
    #date_width = "3.6cm"

    # Optional: sets the font size for the content text
    #font_size = "9pt"

    [layout.fonts]
        regular_fonts = ["Source Sans 3"]
        header_font = "Roboto"

    [layout.header]
        # Optional values: left, center, right
        header_align = "left"

        # Decide if you want to display profile photo or not
        display_profile_photo = true
        # Radius in % to clip profile photo at
        profile_photo_radius = "50%"
        info_font_size = "10pt"

    [layout.entry]
        # Decide if you want to put your company in bold or your position in bold
        display_entry_society_first = true

        # Decide if you want to display organisation logo or not
        display_logo = true

    [layout.footer]
        # Decide if you want to display page counter or not
        display_page_counter = false

        # Decide if you want to display the footer or not
        display_footer = true


[inject]
    # Decide if you want to inject AI prompt or not
    inject_ai_prompt = false

    # Decide if you want to inject keywords or not
    inject_keywords = true
    injected_keywords_list = ["Engineering student", "Python", "SQL", "MatLab", "Simulink", "C", "Control Theory", "Avionics", "UAV", "UAS design", "UAS Operations", "UAS Rules and Regulations"]

[personal]
    first_name = "Guillaume"
    last_name = "Claudon"

    # The order of this section will affect how the entries are displayed
    # The custom value is for any additional information you want to add, name it as custom-1, custom-2, etc.
    [personal.info]
        github = "GuillaumeCldn"
        phone = "+33 6 38 10 98 92"
        email = "gclaudon@yahoo.com"
        linkedin = "guillaume-claudon"
        location = "Toulouse, France"
        # extraInfo = "Available for remote work"
        
        # Custom info with awesome icon
        [personal.info.custom-1]
            # image = "" # Example: image("./path/to/image.png")
            # awesomeIcon = "graduation-cap" # Example: "graduation-cap" see https://typst.app/universe/package/fontawesome/
            # text = "PhD in Data Science"
            # link = "https://www.example.com"
            
        # Linebreak example - adds a line break in header info
        # linebreak = ""

# add a new section if you want to include the language of your choice
# i.e. [[lang.ru]]
# each section must contains the following fields
[lang.de]
    header_quote = "Als Ingenieurstudent an der Ecole Nationale de l'Aviation Civile (ENAC) suche ich ein 14-wöchiges Praktikum ab Juni 2026."
    cv_footer = "Lebenslauf"
    letter_footer = "Anschreiben"

[lang.en]
    header_quote = "Engineering student at ENAC looking for a fourteen week long internship starting in June of 2026."
    cv_footer = "Curriculum vitae"
    letter_footer = "Cover letter"

[lang.fr]
    header_quote = "Elève-ingénieur en deuxième année à l'Ecole Nationale de l'Aviation Civile (ENAC), je suis à la recherche d'un stage de 14 semaines à partir de juin 2026."
    cv_footer = "CV ENAC 2026"
    letter_footer = "Lettre de motivation"
